[workspace]
resolver = "3"
members = ["fume", "fume-core", "fume-reqwest"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GLWTPL"
repository = "https://github.com/dearfl/fume"
keywords = ["steam", "api"]

[workspace.dependencies]
fume = { version = "0.1.0", path = "fume" }
fume-core = { version = "0.1.0", path = "fume-core" }
bytes = "1.11.1"
http = "1.4.0"
reqwest = { version = "0.13.5" }
serde = { version = "1.0.229", features = ["derive"] }
serde_repr = "0.1.20"
serde_json = "1.0.151"
thiserror = "2.0.21"
anyhow = "1.0.102"
tokio = { version = "1.53.1", features = ["full"] }
url = "2.5.8"
