[package]
name = "fume-core"
description = "Steam Web API protocol definitions for fume"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
exclude = [ ".*", "flake.*" ]

[dependencies]
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
thiserror = { workspace = true }

[features]
default = []
deny-unknown-fields = []

[lints.rust]
unsafe_code = "forbid"
